from django.conf.urls import patterns, include, url
from system_views import *


urlpatterns = patterns('',
######STAFF URL
	url(r'/staff/list/$' , system_polls_staff_listing , { 'staff' : True } , name = 'system_polls_staff_listing') ,
	url(r'/staff/add/$' , system_polls_staff_add , name = 'system_polls_staff_add') ,
	url(r'/staff/add/submit/$' , system_polls_staff_add_submit , name = 'system_polls_staff_add_submit') ,
	url(r'/staff/(?P<poll>\w+)/view/$' , system_polls_staff_view , { 'staff' : True } , name = 'system_polls_staff_view') ,
	url(r'/staff/(?P<poll>\w+)/progress/(?P<member>\w+)/$' , system_polls_staff_progress_list , { 'staff' : True } , name = 'system_polls_staff_progress_list') ,
	url(r'/staff/(?P<poll>\w+)/progress/(?P<member>\w+)/(?P<questionnaire>\w+)/view/$' , system_polls_staff_progress_questionnaire_view , { 'staff' : True } , name = 'system_polls_staff_progress_questionnaire_view') ,
	url(r'/staff/(?P<poll>\w+)/logo/upload/submit/$' , system_polls_staff_logo_upload_submit , name = 'system_polls_staff_logo_upload_submit') ,
	url(r'/staff/(?P<poll>\w+)/submit/$' , system_polls_staff_submit , name = 'system_polls_staff_submit') ,
	url(r'/staff/(?P<poll>\w+)/start/$' , system_polls_staff_start , name = 'system_polls_staff_start') ,
	url(r'/staff/(?P<poll>\w+)/select-poll/$' , system_polls_staff_select_poll , name = 'system_polls_staff_select_poll') ,
	url(r'/staff/(?P<poll>\w+)/select-poll/submit/$' , system_polls_staff_select_poll_submit , name = 'system_polls_staff_select_poll_submit') ,
	url(r'/staff/(?P<poll>\w+)/remove-poll/(?P<questionnaire>\w+)/$' , system_polls_staff_remove_poll , name = 'system_polls_staff_remove_poll') ,
	url(r'/staff/(?P<poll>\w+)/select-member/$' , system_polls_staff_select_member , name = 'system_polls_staff_select_member') ,
	url(r'/staff/(?P<poll>\w+)/select-member/submit/$' , system_polls_staff_select_member_submit , name = 'system_polls_staff_select_member_submit') ,
	url(r'/staff/(?P<poll>\w+)/remove-member/(?P<member>\w+)/$' , system_polls_staff_remove_member , name = 'system_polls_staff_remove_member') ,
	url(r'/staff/(?P<poll>\w+)/select-superviser/$' , system_polls_staff_select_member , { 'superviser' : True } , name = 'system_polls_staff_superviser_member') ,
	url(r'/staff/(?P<poll>\w+)/select-superviser/submit/$' , system_polls_staff_select_member_submit , { 'superviser' : True } , name = 'system_polls_staff_superviser_member_submit') ,
	url(r'/staff/(?P<poll>\w+)/progress/members/(?P<member>\w+)/$' , system_polls_staff_progress_members_detail , { 'staff' : True } , name = 'system_polls_staff_progress_members_detail') ,
	url(r'/staff/(?P<poll>\w+)/remove-superviser/(?P<member>\w+)/$' , system_polls_staff_remove_member , { 'superviser' : True } , name = 'system_polls_staff_superviser_member') ,
	url(r'/my_polls/$' , system_polls_my_polls , name = 'system_polls_my_polls') ,
	url(r'/my_polls/(?P<poll>\w+)/view/$' , system_polls_my_polls_view , name = 'system_polls_my_polls_view') ,
	url(r'/my_polls/(?P<poll>\w+)/(?P<questionnaire>\w+)/response/$' , system_polls_my_polls_questionnaire_response , name = 'system_polls_my_polls_questionnaire_response') ,
	url(r'/my_polls/(?P<poll>\w+)/(?P<questionnaire>\w+)/response/submit/$' , system_polls_my_polls_questionnaire_response_submit , name = 'system_polls_my_polls_questionnaire_response_submit') ,
	url(r'/supervised_polls/$' , system_polls_staff_listing , name = 'system_polls_supervised_polls') ,
	url(r'/supervised_polls/(?P<poll>\w+)/view/$' , system_polls_staff_view , name = 'system_polls_supervised_polls_view') ,
	url(r'/supervised_polls/(?P<poll>\w+)/progress/members/(?P<member>\w+)/$' , system_polls_staff_progress_list , name = 'system_polls_supervised_polls_progress_members_detail') ,
	url(r'/supervised_polls/(?P<poll>\w+)/progress/(?P<member>\w+)/(?P<questionnaire>\w+)/view/$' , system_polls_staff_progress_questionnaire_view , name = 'system_polls_supervised_polls_progress_questionnaire_view') ,
######SYSTEM TEST
#	url(r'/test/Fase-I/inventario-talento/$' , system_polls_test_inventario_talento , name = 'system_polls_test_inventario_talento') ,
#	url(r'/test/Fase-I/mapeo-situacional/$' , system_polls_test_mapeo_situacional , name = 'system_polls_test_mapeo_situacional') ,
#	url(r'/test/Fase-I/analisis-desempegno/$' , system_polls_test_analisis_desempegno , name = 'system_polls_test_analisis_desempegno') ,
#	url(r'/test/Fase-II/pre-coaching/$' , system_polls_test_pre_coaching , name = 'system_polls_test_pre_coaching') ,
#	url(r'/test/Fase-III/sesion-1/$' , system_polls_test_sesion_1 , name = 'system_polls_test_sesion_1') ,
#	url(r'/test/Fase-III/sesion-2/$' , system_polls_test_sesion_2 , name = 'system_polls_test_sesion_2') ,
#	url(r'/test/Fase-III/sesion-3/$' , system_polls_test_sesion_3 , name = 'system_polls_test_sesion_3') ,
#	url(r'/test/Fase-III/sesion-4/$' , system_polls_test_sesion_4 , name = 'system_polls_test_sesion_4') ,
#	url(r'/test/Fase-III/sesion-5/$' , system_polls_test_sesion_5 , name = 'system_polls_test_sesion_5') ,
#	url(r'/test/Fase-III/sesion-6/$' , system_polls_test_sesion_6 , name = 'system_polls_test_sesion_6') ,
#	url(r'/test/Fase-IV/analisis-avances/$' , system_polls_test_analisis_avances , name = 'system_polls_test_analisis_avances') ,
#	url(r'/test/Fase-V/reporte-final/$' , system_polls_test_reporte_final , name = 'system_polls_test_reporte_final') ,
)